package model;
// Generated Apr 25, 2020 9:18:43 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int id;
     private String name;
     private String address;
     private String loginName;
     private String password;
     private Boolean gender;
     private Integer age;
     private String phoneNumber;
     private String email;
     private Set invoices = new HashSet(0);
     private Set ratings = new HashSet(0);

    public Client() {
    }

	
    public Client(int id) {
        this.id = id;
    }
    public Client(int id, String name, String address, String loginName, String password, Boolean gender, Integer age, String phoneNumber, String email, Set invoices, Set ratings) {
       this.id = id;
       this.name = name;
       this.address = address;
       this.loginName = loginName;
       this.password = password;
       this.gender = gender;
       this.age = age;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.invoices = invoices;
       this.ratings = ratings;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }




}


