package model;
// Generated Apr 25, 2020 9:18:43 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private int id;
     private Client client;
     private PaymentType paymentType;
     private Date proposedDate;
     private int totalPrice;
     private Integer discount;
     private Integer tatalPriceAfterDiscounting;
     private String note;
     private String address;
     private String phoneNumber;
     private String status;
     private Set productInvoices = new HashSet(0);

    public Invoice() {
    }

	
    public Invoice(int id, int totalPrice) {
        this.id = id;
        this.totalPrice = totalPrice;
    }
    public Invoice(int id, Client client, PaymentType paymentType, Date proposedDate, int totalPrice, Integer discount, Integer tatalPriceAfterDiscounting, String note, String address, String phoneNumber, String status, Set productInvoices) {
       this.id = id;
       this.client = client;
       this.paymentType = paymentType;
       this.proposedDate = proposedDate;
       this.totalPrice = totalPrice;
       this.discount = discount;
       this.tatalPriceAfterDiscounting = tatalPriceAfterDiscounting;
       this.note = note;
       this.address = address;
       this.phoneNumber = phoneNumber;
       this.status = status;
       this.productInvoices = productInvoices;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public PaymentType getPaymentType() {
        return this.paymentType;
    }
    
    public void setPaymentType(PaymentType paymentType) {
        this.paymentType = paymentType;
    }
    public Date getProposedDate() {
        return this.proposedDate;
    }
    
    public void setProposedDate(Date proposedDate) {
        this.proposedDate = proposedDate;
    }
    public int getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(int totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
    public Integer getTatalPriceAfterDiscounting() {
        return this.tatalPriceAfterDiscounting;
    }
    
    public void setTatalPriceAfterDiscounting(Integer tatalPriceAfterDiscounting) {
        this.tatalPriceAfterDiscounting = tatalPriceAfterDiscounting;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getProductInvoices() {
        return this.productInvoices;
    }
    
    public void setProductInvoices(Set productInvoices) {
        this.productInvoices = productInvoices;
    }




}


