package model;
// Generated Apr 25, 2020 9:18:43 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategory generated by hbm2java
 */
public class ProductCategory  implements java.io.Serializable {


     private int id;
     private String name;
     private Set products = new HashSet(0);

    public ProductCategory() {
    }

	
    public ProductCategory(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public ProductCategory(int id, String name, Set products) {
       this.id = id;
       this.name = name;
       this.products = products;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


