package model;
// Generated Apr 25, 2020 9:18:43 PM by Hibernate Tools 4.3.1



/**
 * ProductInvoice generated by hbm2java
 */
public class ProductInvoice  implements java.io.Serializable {


     private int id;
     private Invoice invoice;
     private Product product;
     private int number;
     private Integer totalPrice;
     private Float totalRating;

    public ProductInvoice() {
    }

	
    public ProductInvoice(int id, Invoice invoice, Product product, int number) {
        this.id = id;
        this.invoice = invoice;
        this.product = product;
        this.number = number;
    }
    public ProductInvoice(int id, Invoice invoice, Product product, int number, Integer totalPrice, Float totalRating) {
       this.id = id;
       this.invoice = invoice;
       this.product = product;
       this.number = number;
       this.totalPrice = totalPrice;
       this.totalRating = totalRating;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getNumber() {
        return this.number;
    }
    
    public void setNumber(int number) {
        this.number = number;
    }
    public Integer getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Float getTotalRating() {
        return this.totalRating;
    }
    
    public void setTotalRating(Float totalRating) {
        this.totalRating = totalRating;
    }




}


