package model;
// Generated Apr 25, 2020 9:18:43 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private int id;
     private ProductCategory productCategory;
     private String name;
     private int price;
     private String status;
     private String imagePath;
     private String detail;
     private int leftCount;
     private Integer sellCount;
     private Integer viewCount;
     private Set productInvoices = new HashSet(0);
     private Set ratings = new HashSet(0);

    public Product() {
    }

	
    public Product(int id, String name, int price, int leftCount) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.leftCount = leftCount;
    }
    public Product(int id, ProductCategory productCategory, String name, int price, String status, String imagePath, int leftCount, Integer sellCount, Integer viewCount, String detail, Set productInvoices, Set ratings) {
       this.id = id;
       this.productCategory = productCategory;
       this.name = name;
       this.price = price;
       this.status = status;
       this.imagePath = imagePath;
       this.leftCount = leftCount;
       this.detail = detail;
       this.sellCount = sellCount;
       this.viewCount = viewCount;
       this.productInvoices = productInvoices;
       this.ratings = ratings;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public ProductCategory getProductCategory() {
        return this.productCategory;
    }
    
    public void setProductCategory(ProductCategory productCategory) {
        this.productCategory = productCategory;
    }
    public String getDetail() {
        return this.detail;
    }
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public int getLeftCount() {
        return this.leftCount;
    }
    
    public void setLeftCount(int leftCount) {
        this.leftCount = leftCount;
    }
    public Integer getSellCount() {
        return this.sellCount;
    }
    
    public void setSellCount(Integer sellCount) {
        this.sellCount = sellCount;
    }
    public Integer getViewCount() {
        return this.viewCount;
    }
    
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }
    public Set getProductInvoices() {
        return this.productInvoices;
    }
    
    public void setProductInvoices(Set productInvoices) {
        this.productInvoices = productInvoices;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }




}


