package model;
// Generated Apr 25, 2020 9:18:43 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Rating generated by hbm2java
 */
public class Rating  implements java.io.Serializable {


     private int id;
     private Client client;
     private Product product;
     private String comment;
     private Date commentTime;
     private Integer star;

    public Rating() {
    }

	
    public Rating(int id) {
        this.id = id;
    }
    public Rating(int id, Client client, Product product, String comment, Date commentTime, Integer star) {
       this.id = id;
       this.client = client;
       this.product = product;
       this.comment = comment;
       this.commentTime = commentTime;
       this.star = star;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getCommentTime() {
        return this.commentTime;
    }
    
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }
    public Integer getStar() {
        return this.star;
    }
    
    public void setStar(Integer star) {
        this.star = star;
    }




}


